// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khnwdtgxxssnffombqej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobndkdGd4eHNzbmZmb21icWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzQ1OTEsImV4cCI6MjA2NTUxMDU5MX0.dvbgvBWEK8FtaqWDot0m6dS5xE-Z6tIuYh1rklvYb2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);